### PR TITLE
Document clamps

### PR DESCRIPTION
**Pull request by rick**
Another stab at getting some more readable (and hopefully more actionable) documentation on the clamps module.

/cc @ericwilliamson @acidprime @doug-rosser @mrzarquon

### CODE REVIEW

**Comment by rick** [comment]
[Rendered version](https://github.com/rick/clamps/blob/update-readme/README.md)

**Comment by ericwilliamson** [comment]
You mention which hosts / rules get pinned to each node group, but what about classes?

**Comment by rick** [comment]
@ericwilliamson I don't know enough to be definitive on that -- let's flesh it out!

**Comment by rick** [comment]
Ah, I see where to get that -- I'll add class information in another pass.

**Comment by rick** [comment]
@ericwilliamson I think this is ready for :eyes: again. I added more documentation about classes. :bow:

**Pull request merged**
